import type { Metadata } from 'next';
import { Charm, Inter } from 'next/font/google';
import './globals.css';
import { clsx } from 'clsx';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  variable: '--font-inter',
});

const charm = Charm({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal'],
  variable: '--font-charm',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(inter.variable, charm.variable, 'antialiased')}>
        {children}
      </body>
    </html>
  );
}
